version: 1
disable_existing_loggers: false
formatters:
  short:
    format: "%(levelname)s - %(message)s"
  long:
    format: "%(asctime)s %(levelname)s %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: short
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: long
    filename: ./Log/mr_combolist.log
    maxBytes: 1048576
    backupCount: 10
loggers:
  __main__: 
    level: DEBUG
    handlers:
      - console
      - file
    propagate: false
root:
  level: INFO
